# Generated by Django 3.0.5 on 2020-12-09 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('droids', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Peca',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=255)),
                ('descricao', models.CharField(max_length=255)),
                ('importada', models.CharField(default='Não', max_length=3)),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('data_alteracao', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
